name: highlighter_coachmark
description: Coach Mark shows provided tips or instructions in overlay by blurring background and highlighting target element.
version: 0.0.4
homepage: https://github.com/abednajjar27/highlighter-coachmark.git
maintainer: Marina Kuznetsova (@marica27)

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

# The following section is specific to Flutter.
flutter:
