name: highlighter_coachmark
description: Coach Mark highlights target element and blurs background.
version: 0.0.2
author:  Marina Kuznetsova <marica.tim@gmail.com>
homepage: https://github.com/marica27/highlighter-coachmark
maintainer: Marina Kuznetsova (@marica27)

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

